name: Publish Docker image

on:
  release:
    types: [published]

env:
  DOCKER_IMAGE_REGISTRY: registry.hub.docker.com
  DOCKER_IMAGE_REPOSITORY: ganex/kube-scheduler

jobs:
  deploy:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        id: checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: "amd64,arm64"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      #- name: Build and push Docker image
      #  id: build_publish
      #  uses: jerray/publish-docker-action@master
      #  with:
      #    username: ${{ secrets.DOCKER_USERNAME }}
      #    password: ${{ secrets.DOCKER_PASSWORD }}
      #    registry: ${{ env.DOCKER_IMAGE_REGISTRY }}
      #    repository: ${{ env.DOCKER_IMAGE_REPOSITORY }}
      #    auto_tag: true
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.DOCKER_IMAGE_REGISTRY }}/${{ env.DOCKER_IMAGE_REPOSITORY }}
          #flavor: latest=true
          tags: |
            type=ref,event=pr
            type=semver,pattern={{raw}}
            type=semver,pattern=v{{major}}.{{minor}}
            type=semver,pattern=v{{major}}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          #tags: ${{ env.DOCKER_IMAGE_REPOSITORY }}/test
